module.exports = {

	// Login
	AUTH_CHANGE: 'AUTH_CHANGE',
	AUTH_SIGNIN: 'AUTH_SIGNIN',
	REGISTER: 'REGISTER',

	// Folder
	CREATE_FOLDER: 'CREATE_FOLDER',
	SEARCH_FOLDER: 'SEARCH_FOLDER',
	LOAD_FOLDERS: 'LOAD_FOLDERS',
	DELETE_FOLDER: 'DELETE_FOLDER',

	// Script
	LOAD_SCRIPTS: 'LOAD_SCRIPTS',
	LOAD_SCRIPT: 'LOAD_SCRIPT',
	SAVE_SCRIPT: 'SAVE_SCRIPT',
	SAVE_SCRIPT_AS: 'SAVE_SCRIPT_AS',
	DELETE_SCRIPT: 'DELETE_SCRIPT',
	LOAD_CONFIG_SCRIPTS: 'LOAD_CONFIG_SCRIPTS',

	// Detail
	DETAIL_BASICINFO_UPDATE: 'DETAIL_BASICINFO_UPDATE',
	DETAIL_CONFIG_UPDATE: 'DETAIL_CONFIG_UPDATE',
	DETAIL_PARAMETER_UPDATE: 'DETAIL_PARAMETER_UPDATE',
	DETAIL_ACTION_UPDATE: 'DETAIL_ACTION_UPDATE',
	DETAIL_ACTION_CREATE: 'DETAIL_ACTION_CREATE',
	DETAIL_ACTION_DELETE: 'DETAIL_ACTION_DELETE',
	DETAIL_PARAMETER_CREATE: 'DETAIL_PARAMETER_CREATE',
	DETAIL_PARAMETER_DELETE: 'DETAIL_PARAMETER_DELETE',

	// parameter related
	LOAD_PARAMETERS: 'LOAD_PARAMETERS',
	CREATE_PARAMETER: 'CREATE_PARAMETER',
	DELETE_PARAMETER: 'DELETE_PARAMETER',
	UPDATE_PARAMETER: 'UPDATE_PARAMETER',

	// pacakge rekated
	LOAD_PACKAGES: 'LOAD_PACKAGES',
	UPLOAD_PACKAGE: 'UPLOAD_PACKAGE',
	DELETE_PACKAGE: 'DELETE_PACKAGE',

	// report
	SEARCH_REPORT: 'SEARCH_REPORT',
	LOAD_REPORTS: 'LOAD_REPORTS',
	LOAD_REPORT: 'LOAD_REPORT'
};